---
title: "Analysis"
author: "Bryan Milstead"
date: "Tuesday, February 17, 2015"
output: html_document
---
<!---
use these command instead of the knit icon if you want the data and work loaded into the R workspace
  library(knitr)
  setwd("~/PortableApps/R/scripts/Pia/")
  knit('R/Analysis.rmd')
-->
To Do
-------------------------
* 

Work Notes
-------------------------
201502??
* 

Introduction
-------------------------
* Bird Counts were conducted at sites on the Beagle Channel from Jan.21-31 2015.
* Mist netting was conducted at 3 sites during this period.

Analysis
----------------
* Load data

```{r setup, include=FALSE, echo=FALSE, cache=FALSE} 
  setwd("~/PortableApps/R/scripts/Pia/")
  load('Data/PiaData.rda') 
  library(ggplot2)
```

* Determine plot order for species for areaBirds and mist based on the mean number of counts per area (most abundant to least abundant)
* Note: mist net data and count data harmonized to have the same number of species even if not observed
* Determine plot order for Area-west to east

```{r Obs, include=FALSE, echo=FALSE, cache=FALSE} 
  #convert Obs to long format
    library(reshape2)
    Obs<-melt(Obs,id=3:7,measure=8:22,variable.name='SiteCode',value.name='RelAbund')
  #add site info to obs
    Obs<-merge(Sites[,c('SiteCode','Area','Site')],Obs,by='SiteCode',all.y=T)

  #aggregate Obs by area
    areaObs<-aggregate(Obs$RelAbund,by=list(Obs$Area,Obs$Abbr,Obs$SpanishName),max) #note this deletes rows with "Abbr"==NA
      names(areaObs)<-c('Area','Abbr','NombreComún','maxRelAbund')
```

```{r SpOrder, include=FALSE, echo=FALSE, cache=FALSE} 
  #plotOrder for each species determined by means
    #birds
      a<-aggregate(areaBirds$Mean,by=list(areaBirds$Abbr),mean)
      a<-a[order(a$x,decreasing=TRUE),]
      names(a)[1]<-c('Abbr')
      a$plotOrder<-1:nrow(a)
      Birds<-a[,1]
        #add plotOrder to data-by ordered factors
          areaBirds$Abbr<-ordered(areaBirds$Abbr,levels=Birds)
          mist$Abbr<-ordered(mist$Abbr,levels=Birds)
          areaObs$Abbr<-ordered(areaObs$Abbr,levels=Birds)
            
    #plants
      b<-aggregate(areaPlants$Mean,by=list(areaPlants$Abbr),mean)
      b<-b[order(b$x,decreasing=TRUE),]
      names(b)[1]<-c('Abbr')
      Plants<-b[,1]
        #add plotOrder to data-by ordered factors
          areaPlants$Abbr<-ordered(areaPlants$Abbr,levels=Plants)

```

```{r AreaOrder, include=FALSE, echo=FALSE, cache=FALSE} 
  #plotOrder for each area determined by order west to east
    a<-aggregate(Counts$Easting,by=list(Counts$Area),mean)
    a<-a[order(a$x),]
      names(a)[1]<-'Area'
    Area<-a[,1]
        #add plotOrder to data-by ordered factors
          areaBirds$Area<-ordered(areaBirds$Area,levels=Area)
          mist$Area<-ordered(mist$Area,levels=Area)
          areaObs$Area<-ordered(areaObs$Area,levels=Area)
          areaPlants$Area<-ordered(areaPlants$Area,levels=Area)

```

* Plot Bird counts by area

```{r plotCounts, include=FALSE, echo=FALSE, cache=FALSE} 

#plot areaBirds
  win.graph(11, 8.5) 
  ggplot(areaBirds, aes(x=Abbr, y=Mean)) + 
    geom_bar(position=position_dodge(), stat="identity") +
    geom_errorbar(aes(ymin=Mean-StdErr, ymax=Mean+StdErr),
                  width=.2,                    # Width of the error bars
                position=position_dodge(.9))+
                facet_grid(Area~.) +
                xlab("Bird Species") + 
                ylab(paste('Mean Counts / Station (',expression("\261"),' 1 se)',sep='')) +
                scale_y_continuous(breaks=seq(0, 2, 1)) +
                theme(axis.title.x=element_text(face="bold",size=20,vjust=-.5),
                  axis.text.x=element_text(angle=45, vjust=1.1,hjust=1.1,size=16)) +
                theme(axis.title.y=element_text(face="bold",size=20,vjust=1),
                  axis.text.y=element_text(angle=0, vjust=0.5, size=16))
```

* Plot Mist Net Captures by area

```{r plotMist, include=FALSE, echo=FALSE, cache=FALSE} 

#plot mist
  win.graph(11, 8.5) 
  ggplot(mist, aes(x=Abbr, y=IndividualsAdj)) + 
    geom_bar(position=position_dodge(), stat="identity") +
                facet_grid(Area~.) +
                xlab("Bird Species") + 
                ylab('Mist Net Captures Adjusted for Effort') +
                #scale_y_continuous(breaks=seq(0, 2, 1)) +
                theme(axis.title.x=element_text(face="bold",size=20,vjust=-.5),
                  axis.text.x=element_text(angle=45, vjust=1.1,hjust=1.1,size=16)) +
                theme(axis.title.y=element_text(face="bold",size=20,vjust=1),
                  axis.text.y=element_text(angle=0, vjust=0.5, size=16))
```

```{r plotObs, include=FALSE, echo=FALSE, cache=FALSE} 

#plot areaObs
  win.graph(11, 8.5) 
  a<-areaObs[areaObs$Area!='Seno Yendegaia',] #eliminate Yendegaia
  a<-a[!is.na(a$Abbr),]  #keep only the count and mist species.
  ggplot(a, aes(x=Abbr, y=maxRelAbund)) + 
    geom_bar(position=position_dodge(), stat="identity") +
                facet_grid(Area~.) +
                xlab("Bird Species") + 
                ylab('Maximum Estimated Relative Abundance') +
                scale_y_continuous(breaks=seq(1, 3, 1)) +
                theme(axis.title.x=element_text(face="bold",size=20,vjust=-.5),
                  axis.text.x=element_text(angle=45, vjust=1.1,hjust=1.1,size=16)) +
                theme(axis.title.y=element_text(face="bold",size=20,vjust=1),
                  axis.text.y=element_text(angle=0, vjust=0.5, size=16))
```

```{r plotPlants, include=FALSE, echo=FALSE, cache=FALSE} 
#plot areaPlants
  win.graph(11, 8.5) 
  ggplot(areaPlants, aes(x=Abbr, y=Mean)) + 
    geom_bar(position=position_dodge(), stat="identity") +
    geom_errorbar(aes(ymin=Mean-StdErr, ymax=Mean+StdErr),
                  width=.2,                    # Width of the error bars
                position=position_dodge(.9))+
                facet_grid(Area~.) +
                xlab("Plant Species") + 
                ylab(paste('Presence Proportion (',expression("\261"),' 1 se)',sep='')) +
                scale_y_continuous(limits=c(0,1.1)) +
                theme(axis.title.x=element_text(face="bold",size=20,vjust=-.5),
                  axis.text.x=element_text(angle=45, vjust=1.1,hjust=1.1,size=16)) +
                theme(axis.title.y=element_text(face="bold",size=20,vjust=1),
                  axis.text.y=element_text(angle=0, vjust=0.5, size=16))
```
